# Generated by Django 2.2.6 on 2019-10-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='count',
            field=models.IntegerField(default=10),
        ),
    ]
